name:                ch11-proj
version:             0.1.0.0
github:              "githubuser/ch11-proj"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ch11-proj#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.2.1
- bytestring >= 0.10.12.0
- text >= 1.2.4.1

library:
  source-dirs: 
   - src
   - src/nummod-rank-n
   - src/temperature
   - src/type-families
   - src/type-lits

executables:
  ch11-proj-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch11-proj

tests:
  ch11-proj-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch11-proj
