name:                ch02-proj
version:             0.1.0.0
github:              "githubuser/ch02-proj"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ch02-proj#readme>

dependencies:
- base >= 4.7 && < 5
- fmt >= 0.6.1.1
- mtl >= 2.2.1
- text-show >= 3.8.5
- text >= 1.2.4.1

library:
  source-dirs: 
    - src
    - src/person 
    - src/radar
  default-extensions: LambdaCase, NoStarIsType

executables:
  ch02-proj-exe:
    main:                Main.hs
    source-dirs:         app
    default-extensions: LambdaCase, NoStarIsType
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch02-proj

tests:
  ch02-proj-test:
    main:                Spec.hs
    source-dirs:         test
    default-extensions: LambdaCase, NoStarIsType
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch02-proj
